# Generated by Django 2.1.8 on 2019-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.CharField(default='', max_length=300),
        ),
    ]
