# Generated by Django 2.1.8 on 2019-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
