# Generated by Django 2.1.8 on 2019-05-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchGradeNm',
            field=models.CharField(default='', max_length=150),
        ),
    ]
