# Generated by Django 2.1.8 on 2019-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_watchgradenm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='score',
            name='movieCd',
            field=models.IntegerField(default=0),
        ),
    ]
